const siteMetadata = {
    title: '',
    author: '',
    headerTitle: '',
    description: '',
    language: '',
    theme: '', 
    siteUrl: '', 
    siteLogo: '',
    socialBanner: '',
    email: '', 
    github: '',
    twitter: '',
    facebook: '',
    youtube: '',
    linkedin: '',
    dribbble: '',
    locale: '',
  }
  module.exports = siteMetadata